name: PR-CI-CD

on:
  pull_request:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create env file
        run: |
          echo $env_var
        env:
          # Setting an environment variable with the value of a configuration variable
          env_var: asdadadasdad
      - name: Install Dependencies
        run: |
          npm install
      - name: Snyc Template Versions
        run: |
          node index.js ${{ vars.CAMPAIGN_TEMPLATE_ID }}