name: PR-CI-CD

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create env file
        run: |
          touch .env
          echo AAAAAA="${{ secrets.SENDGRID_API_KEY }}\n"  >> .env
          echo DDDDDD=${{ vars.FILE_PATH }} >> .env
          cat .env
      - name: Install Dependencies
        run: |
          echo $AAAAAA
          echo $DDDDDD
          npm install
      - name: Snyc Template Versions
        run: |
          node index.js ${{ vars.CAMPAIGN_TEMPLATE_ID }}