name: PR-CI-CD

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create env file
        run: |
          touch .env
          echo ENGINE_API_KEY=${{ secrets.ENGINE_API_KEY }} >> .env
          echo FILE_PATH=${{ secrets.FILE_PATH }} >> .env
      - name: Create env file
        run: |
          npm install
      - name: Snyc Template Versions
        run: |
          node index.js ${{ secrets.CAMPAIGN_TEMPLATE_ID }}