name: PR-CI-CD

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          npm install
      - name: Snyc Template Versions
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }} 
        run: |
          node index.js ${{ vars.CAMPAIGN_TEMPLATE_ID }}