name: PR-CI-CD

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          npm install
      - name: Snyc Template Versions
        env:
          SENDGRID_API_KEY1: ${{ secrets.SENDGRID_API_KEY }} 
          SENDGRID_API_KEY2: ${{ vars.CAMPAIGN_TEMPLATE_ID }} 
          SENDGRID_API_KEY3: ${{ vars.FILE_PATH }} 
        run: |
          
          echo $SENDGRID_API_KEY1
          echo $SENDGRID_API_KEY2
          echo $SENDGRID_API_KEY3
          node index.js ${{ vars.CAMPAIGN_TEMPLATE_ID }}