name: PR-CI-CD

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Snyc Template Versions
        env:
            SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
            FILE_PATH: ${{ secrets.FILE_PATH }}
        run: |
          node index.js ${{ secrets.CAMPAIGN_TEMPLATE_ID }}