name: PR-CI-CD

on:
  pull_request:
    branches: [main]
env:
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create env file
        run: |
          echo $SENDGRID_API_KEY
      - name: Install Dependencies
        run: |
          echo $SENDGRID_API_KEY
          npm install
      - name: Snyc Template Versions
        run: |
          echo $SENDGRID_API_KEY
          node index.js $CAMPAIGN_TEMPLATE_ID